// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"myproject/internal/db"
	"myproject/pkg/handlers"
)

// Injectors from wire.go:

func InitializeUserHandler() (*handlers.UserHandler, error) {
	config, err := db.NewDBConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.NewDB(config)
	if err != nil {
		return nil, err
	}
	userRepository := db.NewUserRepository(sqlDB)
	userHandler := handlers.NewUserHandler(userRepository)
	return userHandler, nil
}
